# Generated by Django 3.1 on 2020-08-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcshop', '0003_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
